<?php 

/*
SQL injection, sql sorgularina bizim kendi sorgularimizi enjekte etmekle olusan birsey
*/
//$id=1;
$id="''; DROP TABLE USERS;";
//BU NORMALDE BIZE ORNEGIN BIR KULLANICI UYGULAMMIZI KULLANIRKEN FILTRELEME YAPIYOR SEARCH ISLEMI YAPIYOR VE BIR INPUTA GIRDIGI DEGERI BIZ ARATTIRIYORUZ ORNEGIN, KULLANICIDAN ALDIGMZ DEGERI EGER BIZ DOGRUDAN GETIRIP DE SQL SORGUMUZA YAZARSAK, KULLANICININ TUTUP DA INPUT ICERISINE "''; DROP TABLE USERS;" BOYLE BIR SEY YAZMA IHTIMALINDE BU SORGU SONUCTA GIDIP VERITABANINDA CALISTIRILIYOR VE KULLANICI NE YAPTI BIZIM SORGUMUZU BURDA NE HALE GETIRDI, TABLOYU SILECEK BIR SQL SORGUSU GONDERDI ADAM RESMEN VE BIZ HIC FARKINDA BILE DEGILIZ DOGRUDAN TABLOMUZU SILER VE DE COK BUYUK SKNTI YASAYABILIRIZ 
//ADAM INPUTA BOYLE BIRSEY GIRERSE RESMEN BIZIM SISTEMIMIZ COKERTMIS OLUYOR
//ORNEGIN BIR FORM DOLDURUP GONDERECEK VE BIZ O FORMDAN GELEN DATAYI DOGRUDAN ALIP, SQL SORGUMUZ ICNE YAZMA DURMUNDA O ZAMAN COK BUYUK TEHLIKE YASAMA RISKI ILE KARSI KARSIYA OLUYORUZ ISTE 
//INPUT ICINE ";DROP TABLE USERS; DISARDAN SORGUMUZA MUDAHELE ETMIS OLUYOR RESMEN
//ISTE BU TEHLIKELERE KARSI SISTEMIMIZI VE SORGUMUZ KORUMA ALTINA ALMAK ICIN, KESINLIKLE EGER DISARDAN VERI ALARAK BIR SORGU YAPIYOR ISEK MUTLAAKA PREPARE VE EXECUTE METHODU ILE BU ISLEMLERI YAPMALIYIZ
//EGER ISTERSEK HER IHTIMALE KARSI DA SORGU ICINDE KULANACAIGMZ POST MNETHODU ILE KULLANICIDAN GELECEK DEGERI BIZ YINE NE OLUR NE OLMAZ DIYE 
$epost=htmlspecialchars($_POST["epost"], ENT_QUOTES);//kULLANARAK, GONDERILEN EPOST DATA SININ TIRNAKLARINI KALDIRARAK EGER BIR SQL KODU YAZILMIS ISE BIZIM SQL SORGUMUZA SIZMAK VE MUDAHELE ETMEK ICN, O ZAMAN ONUN TIRNAKLARINI KALDIRARAK ONUN SORGUYA MUDAHELESI DE ENGELLENEBILIR ASLINDA AMA HER HARUKARDA BIZ PREPARE-EXECUTE ILE SORGULARMIZ YAPMALIYZ HTMLSEPECIALCHARS I KULLANSAK BILE

$sql="SELECT * FROM USERS WHERE ID=".$id;
echo $sql;
//ORNEGIN BU SEKILDE BIR SORGU YAZDIK, BIZIM BURDAN KULLANICIDAN ALACAGIMZ DEGER ID DEGERINI 1 ALACAGIZ BU KULLANICIDAN GELECEK 
//YANI BURDA DISARDAN GIRECEGIMIZ DEGER ID DIR

//BESTPRACTISE.. CIFT TIRNAK ICINDE, BIR DE TEK TIRNAK ACIP DA YAZMAMIZ GEREKEN DATALARI DINAMIK YAZARKEN DISARDAN DEGISKEN OLARAK ALIYORUZ VE ONLAARI YAZARKEN MANTIGIMIZ SU OLACAK KARISITRMAMAK ICIN BURAYA DIKKAT EDELIM ...
//  "       ' BURAYA DEGISKEN YAZACAGZ ".$id."      '   ";
//CIFT TIRNAKLAR ICINDEKI TEK TIRNAKLARI ICNE YAZACAGMIZ ZAMAN ONCE EN SOLDA ILK OLARAK ACILMIS OLAN EN DIS TIRNAGI KAPATIRIZ ARDINDAN 2 TANE . $id  . BIRLESTIRME OPERATORU ARASINA DEGISKNEIMIZI YAZARIZ ARDINDAN DA EN BASTA KI CIFT TIRNAGI TEKRAR BASLATIARAK DEVAM EDERIZ   

/*
SIMDI BIZ YUKARDAKI SQL SORGUSUNDA 5 YERINE BIZ "'';DROP TABLE USERS" YAZILSA ID ID YERINE EGER BOYLE BIRSEY YAZILMIS OLSA IDI O ZAMAN SQL SORGUSU DEGISECEKTTI
SELECT * FROM USERS WHERE ID=1
SELECT * FROM USERS WHERE ID=''; DROP TABLE USERS; 
BU SEKILDE DISARDAN EKSTRA SORGU ENJEKTE EDILMIS OLURDU EGER ID YERINE BASKA BIRSEY YAZILMA DURUMUNDA 
YANI KULLANICIDAN ALINAN ID GIBI SORGULAR ICINDE KULLANMAKICIN ALDGIMIZ VERILERI EGER FILTRELEMEDEN SQL SORGULARINA DAHIL EDERSEK BU BIR INJECTION ACIGINI ORTAYA CIKARACAKTIR
*/

?>