<?php 

//1-curl i balat
$curl=curl_init();

//2-curl ayarlarini yap
curl_setopt_array($curl,[
    CURLOPT_URL=>"http://localhost/test/PHP-works/php-cURL/php-curl-sending-browser-data/",
    CURLOPT_RETURNTRANSFER=>true,
    // CURLOPT_USERAGENT=>$_SERVER["HTTP_USER_AGENT"]
    CURLOPT_USERAGENT=>"Mozilla/5.0 (Linux; Android 12; SM-S906N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36"
    //$_SERVER["HTTP_USER_AGENT"] BU BROWSER MOBIL BROWSER OLURSA MOBIL BROWSER I ACACAK
    //USER AGENT STRINGS DIYE ARATTIRIRSAK EGER ORDAN ORNEGIN ANDROID ICIN VERILEN USER_AGENT I ALIP BURAYA YAPISTIRIRZ VE O ZAMAN BAGLANMAK ISTEDGMIZ SITENIN MOBIL VERSIYONUNA BAGLANABILIRIZ VEYA DA ISTE DIGER VERSIYONLARI ILE ILGILI HAZIR USER AGENT STRINGLERI ALARAK ONLARI BURDA KULLANIP ONLARA DA BAGLANABILIRZ,DESKTOP,MOBIL VERSIYON VS GIBI
]);

//3-curl executte ederiz
$source=curl_exec($curl);

//4-curl i kapatiriz
curl_close($curl);

echo $source;

//Warning: Undefined array key "HTTP_USER_AGENT" in  
//kendi index.php mize baglanmak istedgmizde bize boyle bir warning mesaji veriyor, neden cunku biz curl i kullanarak bir browser bilgisii gonderemiyoruz  yani normal browser dan istek atinca direk url uzerinden USER_AGENT BROWSER BILGISI GONDEREBILIRKEN CURL ILE BAGLANIP DATASINI CEKMEK ISTEDGIMZ ADRESE BROWSER BILGISI GONDEREMEDIGMIZ ICIN BURDA DA DOGAL OALRAK UNDEFINED ALIYORUZ CUNKU BAGLANMAYA CALIISTIGIMIZ SITE echo $_SERVER["HTTP_USER_AGENT"]; EKRANA BROWSER BILGISINI BASTIK ONU CURL ILE BURAYA BAGLANARAK ALABILIR MIYIZ DIYE AMA BU SEKILDE ALAMADIK O ZAMANDA YINE BIZIM BAGLANMYA CALISTGIMIZ ADRESS TE DE DEMEKKI IF(!ISSET($_SERVER["HTTP_USER_AGENT"])) ISE BOT GIRISIMI ENGELLENDI DIYE YAZABILIR, TARAYICI BILGISI OLMADAN ISTEK GONDEREN LER BOT DEMEKTIR GIBI BIR SONUC CIKARABILIRIZ BURDA
//Bu engeli asabilmek iicinde yine bir ayar ekleyecegiz CURLOPT_USERAGENT SEKLINDE CURLOPT_USERAGENT=>$_SERVER["HTTP_USER_AGENT"] DERSEK SISTEMIN TARAYICI BILGISINI GONDERECEKTIR, BU SEKILDE BOT ATTIGMIZ SISTEMIN ALDIGI HTTP_USER_AGENT CHECK ETME GUVENLIGINI DE ASMIS OLUYORUZ

?>