<?php 

session_start();

if (isset($_SESSION['id']) && isset($_SESSION['user_name'])) {

?>

<!DOCTYPE html>

<html>

<head>

    <title>HOME</title>

    <link rel="stylesheet" type="text/css" href="style.css">

</head>

<body>

     <h1>Hello, <?php echo $_SESSION['name']; ?></h1>

     <a href="logout.php">Logout</a>

</body>

</html>

<?php 

}else{
     //HOMEPAGE E KULLANICI URL DEN DUSERSE VEYA TIKLAMA ILE DE GELIRSE ILK ONCE HEMEN BIR SESSION KONTROLUNDEN GECER...YANI KULLANICI GIRIS Y APMIS MI ONU SESSION ICINDEKI DATALARDAN KONTROL EDERIZ EGER KULLANICI GIRIS LI ISE LOGIN OLMUS ISE O ZAMAN KULLANICI YA ADMIN SAYFASI OLUR VEYA HANGI SAYFALARIMIZ VAR ISE LOGIN OLDUGUNDA GIRMESINE IZIN VERDIMGZ ONLARIN HEPSINE GIREBILIR VE ARTIK LOGOUT BUTONUNU GORMELIDR KI CIKMAK ISTERSE CIKABILSIN...
     //AMA KULLANICI GIRIS YAPMADAN GELMIS ISE, ISTE O ZAMAN KULLANICI FORM UN OLDUGU SAYFA HANGI SAYFA ISE YANI LOGIN FORMUNUN OLDUGU SAYFA HANGI SAYFA ISE O SAYFYA YONLENDIRILIR
     header("Location: index.php");

     exit();

}

 ?>