<?php 

$tutorial_id=$_GET['id'];
//GROUP_CONCAT ILE BIZ HER BIR TUTORIAL DETAYI KARSISINA SAHIP OLDUGU COKLU KATEGORILERIN YANINDA ISIM ISIM ARARALARINDA VIRGULLE YAZILARAK 
//GELMESINI SAGLARIZ
//FIND_IN_SET SAYESINDE HER BIR UNIQ CATEGORIES TABLOSUNDAKI CATEGORY ID SININ TUTORIALS TABLSOUNDAKI CATEGORY_ID "5,6,7" GIBI STRING SEKLINDEKI ID LER ICINDE VAR OLANLARI LISTELIYOR AMA TUTORIAL LAR AYNI SADECE FARKLI KATEGORILERE SAHIP OLLMALARINA GORE LISTELIYOR VE BURDA DEVREYE GROUP BY GIREREK AYNI ID DEKI TUTORIAL LARI GROUPLANDIIRYOR BIZIM ICIN BU SEFER DE BIZE HER BIR TUTORIAL IN HANGI FARKLI KATEGORILERE SAHIP SE ONLARIN ISIMLERI ILE BIRLIKTE GELMESI ICINDE GROUP_CONCAT DEVREYE GIREREK GROUP_BY-GROUP-CONCAT VE FIND_IN_SET UCU BIRLIKTE HARIKA BIR IS CIKARIYORLAR BIZIM ICIN...TABI BUNLARIN HEPSINI JOIN EDILMIS BIR TABLO ICERISINDE KULLANIYORUZ...
$tutorial_detail=$db->query("SELECT tutorials.*, GROUP_CONCAT(categories.name) as category_name FROM tutorials inner join categories on FIND_IN_SET(categories.id,tutorials.category_id)  WHERE tutorials.id=$tutorial_id  GROUP BY tutorials.id")->fetchAll(PDO::FETCH_ASSOC);
//print_r($tutorial_detail);
?>


<?php //require_once "header.php"; index.php ye dahil ettigmiz icin burda zaten gozukecek ondan dolayi burda kullanmaya gerek yok?> 

<!-- BURASI DIKKAT EDELIMM HER BIR KAYITA TIKLAYINCA GET_ ID SI ILE BURAYA GELIYOR ID DINAMIK GELIYOR BURDA
HANGI DATAYA TIKLANDI ISE O DATA ID IS ILE BURAYA GELIYOR
-->
<?php 
//http://localhost/PHP-works/pdodatabase/php-pdo/index.php?page=read&id=2
//BURDA DA YINE AYNI HATAYI ALDIK DIKKAT EDELIM SADECE, ISSET ILE ID YI YOKSA DIYE KONTROL ETMEK ISIMIZI GORMUYOR CUNKU ID $_GET DIZISI ICINDE KEY OLARAK GELIYOR VE ISSET KONTROLUNDEN TRUE OLARAK GECIYOR ANCAK....VALUE OLARAK BOS STRING GELIYOR O ZAMAN DA BIZIM ISLEMIMIZI GERCKELSTIRMIYOR DOLAYISI ILE BIZIM SADECE ISSET KONTROLU ILE ISIMIZ GORULMYYOR ONCE ISSET KONTROLU ARDINDAN DA VAR AMA ICI BOS MU, STRING OLRAK BOS BIR STRING OLARAK MI GELMIS ONU DA KONTROL ETMEK GEREKIYOR
if(!isset($_GET['id']) || empty($_GET['id'])){
//Eger get ile url de id yok ise o zaman direk sayfayi index.php ye yonlendirmek istyoruz
header('Location:index.php');
exit;//exit ile de sonrasini calistirmayalim
}else {
    $id=$_GET['id'];
    //Burda id yi alabildimgize gore o zaman burda biz veritabanindan select ile id yi filtreleyerek tek bir data  cekelim, o zaman fetch kullaniriz
    //COOOK ONEMLI YAKLASIMLARDAN BIR TANESI DE BURDA ...COK IYI ANLAMALIYIZ
      //BURDA CONFIRMI FALS OLANIN DETAY ICERIGINI DE GOSTERMEYECEGIZ BUNA DA DIKKAT EDELIM..EGER VERITABANINDAKI KOLONLARIMIZ ICINDEKI BOOLEAN-TYNINT-0-1 VALUE OLAN DEGERLERIN DURUMUNA GORE BAZI DATALARI GOSTERSIN BAZI DATALARI GOSTERMESIN DIYORSAK O ZAMAN DIREK SELECT SORGUUSU ICINDE YAPACAGIZ BU ISLEMI ONA DIKKAT EDELIM....FILTRELEMELRDE ILK AKLIMZA SU GELSIN BIZ BU ISLEMI DIREK SELECT ISLEMI ILE DATABASE SORGUSUNDA MI ELE ALIYORUZ YOKSA SONRASINDA MI AMA PHP DILI BACKEND DILI OLDUGU ICIN BU DIL VERITABANI SORGULARINDA COK GELISMIS GORDGUMZUZ KADARI ILE VE GENELLIIKLE TYPIK OLARAK FILTRELEMER VS VERITABANI SORGULARINDA ELE ALINIYOR....
    $query=$db->prepare('SELECT * FROM tutorials WHERE id=:id && confirm=:confirm');
    $query->execute([':id'=>$id, ':confirm'=>1]);//ONAYI 0 OLAN DATALAR ICIN DE TUTORIAL BOS GELECEGI ICIN INDEX.PHP YE YONLENDIRECEK ONAYI 0 OLAN DATA YA URL DEN GIRMEYE CALISIRSA KULLANICII...ISTE BUNA COOK DIKKKAT EDELIM...REACTTA DA BIZ AYNI SEYLERI PLANLIYORDUK..BURDA DA BENZER SEYLERI COK IYI PLANLAMALIYIZ...
    $tutorial=$query->fetch(PDO::FETCH_ASSOC);
    //BESTPRACTISE..
    //PEKI ID GONDEIRLIYOR AMA VERITABANINDA OLMAYAN BIR ID ISE YANI BIZ DATAMIZI ID OLARAK VERITABNINDAN ALDIK TEK BIR DATA OLARAK
    //ARADIGIMIZ GETIR DEDGIMZ ID YOK ISE, WHERE ILE ARADIGMIZ DATA NIN GELMEMEM VEIRTABANINDA OLMAMA IHTIMALINI HER ZAMAN DUSUNMELIYIZ
    //KULLANICI TIKLAYRAK GELSE BILE DIREK URL E YAZILABILECEK FARKLI BIR ID DE NE GIBI FARKLI SONUCLAR OLABILIR BUNLARI BIZIM ONGOREBILMEMIZ GEREKIR YANI HERSEY BIZIM TIKLAMAMIZ ILE GELISMIYOR BIZ HER ZAMAN URL DEN DIREK YAPILABILECEK DENEMELERDE, FARKLI DENEMELERDE UYGULAMAMIZ NE GIBI TEPKILER VERIYOR NASIL DIRENC GOSTERIYOR BUNLARI CEK EDIP ONLEM ALMAMIZ GEREKKIYOR....
    
    if(!$tutorial_detail)
    {
        //BU SEKILDE UYGULAMAMIZI KORUMUS OLUYORUZ UYGULAMAMIZDA BIRISI URL DEN OLMAYAN BIR ID GIRERSE DE O ZAMAN ANA SAYFAYA YONLENDIREREK ASLINDA BIR HATA OLMA IHTIMALINI YA DA BELIRSZ LIK OLMA IHTIMALINI DE ORTADAN KALDIRMIS OLUYORUZ....BESTPRCTISE...BU MANTIGI HER ZAMAN DUSUNMELIYIZ...
        header('Location:index.php');
    }
    // print_r($tutorial_detail[0]['id']);
    foreach ($tutorial_detail as $key=> $value) {
        $confirm=$value['confirm']==1 ? "Confirmed":"Unconfirmed";
       echo   "title:  ".$value['title']. "</br>".
              "category:  ".$value['category_name']. "</br>".
              "contain:  ".$value['contain']. "</br>".
              "confirm:  ".$confirm. "</br>".
              "Publish-date:  ".$value['date']. "</br><hr>"
              ;
              
    }

}
//BESTPRACTISE--YUKARDA KI KULLANIM COK FAZLA UYGULAYACAGIMZ YONTEMLERDEN BIR TANESIDIR...COK CIDDI ASINA OLMALIYIZ...BU KULLANIMA

?>
<!-- YINE BURDA DA YAPTIM O HATAYI ECHO ILE GOSTERMEDEN EKRANA DATA GELMIYOR....BEN DIREK JSCRIPT GIBI VEYA DIGER DILLER GIBI DUSUNYORUM AMA BURDA ECHO ILE GOSTERMDEN DATA GELMIYOR -->
<h3> <?php // echo $tutorial['title']  ?> </h3>
<div>
 <strong> <?php  // echo $tutorial['date'] ?></strong>
 <?php //echo "</br> <hr>"; ?>   
<?php //echo $tutorial['contain']."</br>"   ?>
<?php// echo nl2br($tutorial['contain'])//icerigin alt alta olanlarin burda da alt alta gozukmesi icin   ?>

</div>

<!-- 

$tutorial_id=$_GET['id'];
$tutorial_detail=$db->query("SELECT tutorials.*, categories.name FROM tutorials
 inner join categories on categories.id=tutorials.category_id
 WHERE tutorials.id=$tutorial_id")->fetchAll(PDO::FETCH_ASSOC);


NOT-BESTPRACTISE: YAKLASIM TARZIMIZ VE BAKIS ACIMZI HER ZAMAN BASIT TUTMAK-KOMPLEKS VE KARMASIK OLMASI YERINE..
 YAKLASIM TARZIMI ACISINDAN TEK SORGU YAZDIK VE BURDA BIZ HEM TUM TUTORIALS I ALDIK 
 HEM DE CATEGORY NAME I ALDIK TAMMAM OK ANCAK BIZ IM ELIMIZDE ZATEN BU TUTORIAL IN HANGI
  CATEGORY ID SINE AIT OLDUGU VAR BIZ BU CATEGORY ID SNI KULLANARAK DIREK CATEGORIES 
  TABLOSUNDAN CATEGORY YE AIT DETAYLARI DA ALIP BU SAYFADA COK KOLAY BIR SEKILDE
   GOSTEREBILIRIZ 2 FARKLI SORGU YAPMIS OLURUZ AMA HIC JOIN YAPMADAN COK KOLAY BIR 
   SEKIDLE 2 TANE BASIT SELECT QUERY LERI YAPARAK ISI COK KOLAY BIRSEKILDE COZEBILIRDIK..
   BIZ BU TARZ INNER JOIN-VS GIBI KARMASIK SORGULARI ANCAK ZORUNDA KALDIGIMZ ZAMAN YAPMALIYIZ 
, YANI EGER BIZ COK DAHA BASIT SORGULAR ILE IHTIYACIMZ OLAN DATAYA ERISIYORSAK BU SEKILDE
GEREKSIZ SEKILDE YAPTIGIMZ ISLEMLERI KOMPLEKS HALE GETRIMEK YAZILIMIN KALITESNI ARTTIRMAZ
    TAM TERSI ANLASILMAYI VE UYGULAMANIN BAKIMINI ZORLASTIRIR ONDAN DOLAYI ANA MANTIGIMIZ 
    HER ZAMAN OLABILDIGINCE BASIT DUSUN VE BASIT SEKILDE KALICI COZUMLER URET..ADVANCE ISLEMLER
    EGER IHYTYAC ISE UYGULANMALIDIR YOKSA SIRF ONU UYGULAYABILDIGINI GOSTERMEK ICIN UYGULANMAZ 
    OYLE SEYLER YARIN OBURGUN ANLAMAYI DA ZORLASTIRIR VE KENDI KNEDIMIZE YA NIYE BOYLE BIR SORGU
    YAPMISIM ZATEN KOLAY BIR SEKILDE CATEGORY NAME E ERISEBILYORUZ DIYE KENDI KENDINMIZE SORARIZ....
-->