<?php 
/*
SQL-SORGU-YAPILANDIRILMIS SORGU DILI
STRUCTURED QUERY LANGUAGE

MYSQL
Mysql bir urundur
RDMS-RELATIONAL DATABASE MANANGEMENT SYSTEM
Veritabani yonetim sistemidir

SQL BIR DILDIR
MYSQL- BIR RELATIONAL DATABASE MANANGEMENT SYSTEM
BIZ MYSQL ICINDE SQL KODLARINI KULLANIYORUZ

TUM ILISKISEL VERITABANI YONETIMI SISTEMLERI DIL OLARAK SQL I KULLANIRLAR
MSSQL,MYSQL,ORACLE,POSTGRE
HERBIRININ KULLANDIGI SQL SORGULARINDA COK KUCUK FARKLILIKLAR VARDIR

TEMELDE YAPILAN SEY ASLINDA SQL SORGULARIDIR...


*/

?>